name: Security & Dependencies

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
  push:
    paths:
      - 'pixi.toml'
      - 'pixi.lock'
      - 'pyproject.toml'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.34.0
        cache: true

    - name: Install dependencies
      run: pixi install

    - name: Run security audit
      run: |
        # Check for known vulnerabilities in Python packages
        pixi run python -m pip list --format=json | \
        pixi run python -c "
        import json, sys, subprocess
        packages = json.load(sys.stdin)
        for pkg in packages:
            try:
                result = subprocess.run(['pixi', 'run', 'python', '-m', 'pip', 'show', pkg['name']], 
                                      capture_output=True, text=True)
                print(f\"✓ {pkg['name']} {pkg['version']}\")
            except Exception as e:
                print(f\"⚠️  {pkg['name']}: {e}\")
        "

    - name: Check for outdated dependencies
      run: |
        echo "Checking for outdated dependencies..."
        pixi info

  dependency-update:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.34.0
        cache: true

    - name: Update dependencies
      run: |
        # Update pixi lock file
        pixi update
        
    - name: Test with updated dependencies
      run: |
        pixi install
        pixi run test

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          Automated dependency updates from scheduled workflow.
          
          This PR updates dependencies to their latest compatible versions.
          
          Please review the changes and run tests before merging.
        branch: automated-dependency-updates
        delete-branch: true